allow-expect-in-tests = false
allow-mixed-uninlined-format-args = false
allow-unwrap-in-tests = false
allowed-scripts = []
arithmetic-side-effects-allowed = []
avoid-breaking-exported-api = true
await-holding-invalid-types = []
cognitive-complexity-threshold = 20
doc-valid-idents = []
enable-raw-pointer-heuristic-for-send = false
enforced-import-renames = []
enum-variant-name-threshold = 30
enum-variant-size-threshold = 30
ignore-interior-mutability = []
large-error-threshold = 60
literal-representation-threshold = 60
max-fn-params-bools = 3
max-include-file-size = 100000
max-struct-bools = 3
max-suggested-slice-pattern-length = 3
max-trait-bounds = 3
pass-by-value-size-limit = 3
single-char-binding-names-threshold = 3
third-party = false
too-large-for-stack = 200
too-many-arguments-threshold = 7
too-many-lines-threshold = 200
trivial-copy-size-limit = 3
type-complexity-threshold = 200
unreadable-literal-lint-fractions = true
upper-case-acronyms-aggressive = true
vec-box-size-threshold = 3
verbose-bit-mask-threshold = 3
warn-on-all-wildcard-imports = true