// Loft Language Reference — generated by `cargo run --bin gendoc`
// Compile with: typst compile loft-reference.typ loft-reference.pdf

#set document(title: "Loft Language Reference")
#set page(paper: "a4", margin: (x: 2.5cm, y: 3cm))
#set text(font: ("Libertinus Serif", "Liberation Serif", "DejaVu Serif"), size: 11pt)
#set par(justify: true, leading: 0.75em)
#set heading(numbering: "1.1.")

#show raw.where(block: true): it => block(
  fill: luma(245),
  inset: (x: 10pt, y: 8pt),
  radius: 4pt,
  width: 100%,
  it,
)

#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  v(0.5em)
  it
}

= Loft Language Reference

#v(1em)

_A statically-typed scripting language inspired by Rust, designed for embedding in the Dryopea engine._

Every code example in this document is an executable part of the test suite.

#outline(depth: 3)

#pagebreak()

= Keywords

Core syntax: if/else expressions, for loops, break/continue, and named breaks for nested loops.

```rust
fn main() {
```

=== Conditionals

A program can be stopped by calling the panic function. Production code will never panic, the problem will only be logged.

```rust
    if 2 > 5 {
       panic("Incorrect test");
    }
```

Boolean expressions can be written with gradually more complex logic. Both '&&' '||' and 'and' 'or' can be used in logical expressions. The '&' expression is the binary and operation.

```rust
    a = 12;
    if a > 10 and a & 7 == 4 {
        a += 1;
    } else {
        a -= 1;
    }
```

Each text constant can contain formatting expressions. In production code the assert statements are omitted, so the code will not stop on each found problem. While debugging the asserts will be evaluated and logged.

```rust
    assert(a == 13, "Incorrect value {a} != 13");
```

Each block returns its last expression, so an if statement can be used as an expression.

```rust
    b = if a == 13 { "Correct" } else { "Wrong" };
    assert(b == "Correct", "Logic expression");
```

=== Iteration

A simple for loop that including 1 and omits 6.

```rust
    t = 0;
    for a in 1..6 {
        t += a;
    }
    assert(t == 15, "Total was {t} instead of 15");
```

Loop the reverse of a range. Here, 'rev' disguises itself as a normal function.

```rust
    t = 0;
    for a in rev(1..=5) {
        t = t * 10 + a;
    }
    assert(t == 54321, "Result was {t} instead of 54321");
```

=== Nested Loops and Break

This language doesn't contain a 'loop' or 'while' style loop. Treat this as a limiter to prevent hanging loops. There is always a loop variable which can be used as the name of the loop. The length is requested via 'len' that acts like a function on strings or other data structures.

```rust
    b = "";
    for x in 1..5 {
        for y in 1..5 {
            if y > x {
                break; // this breaks the inner y loop
            }
            if x * y >= 16 {
                x#break;
            }
            if len(b) > 0 {
                b += "; ";
            }
            b += "{x}:{y}";
        }
    }
    assert(b == "1:1; 2:1; 2:2; 3:1; 3:2; 3:3; 4:1; 4:2; 4:3", "Incorrect sequence '{b}'");
```

=== Loop Helpers: \#first and \#count

To limit the common creation of helper variables it is allowed to request the '#first' or '#count' in a loop. This is similar to the x.iter().enumerate() construction in rust. Though here, it functions with an 'if' filter.

```rust
    b = "";
    for x in 1..=9 if x % 3 != 1 {
        if !x#first {
            b += ", ";
        }
        b += "{x#count}:{x}";
    }
    assert(b == "0:2, 1:3, 2:5, 3:6, 4:8, 5:9", "Sequence '{b}'");
}
```


= Texts

UTF-8 strings: byte-based indexing, slices, concatenation, formatting, and built-in functions.

```rust
fn main() {
```

=== Creating and Measuring Strings

Text concatenation produces a new string.

```rust
    a = "1" + "2";
    assert("'{a:4}'" == "'12  '", "Formatting text");
    assert(len(a + "123") == 5, "Text length");
```

len() counts bytes, not Unicode code points. A multi-byte emoji occupies 4 bytes; a heart symbol occupies 3 bytes.

```rust
    assert(len("😃") == 4, "Emoji byte length");
    assert(len("♥") == 3, "Heart byte length");
    assert(len("abc") == 3, "ASCII byte length");
```

Indexing a string with [n] returns the character whose UTF-8 encoding contains byte n. For ASCII strings, byte index equals character index.

```rust
    s = "ABCDE";
    assert(s[0] == 'A', "Character at byte 0");
    assert(s[2] == 'C', "Character at byte 2");
```

A range index extracts a sub-string by byte offsets. The upper bound is exclusive; omitting it goes to the end. Both 'start' and 'end' must be explicit when both are given. Open-start slices (s[..n]) are not supported — use s[0..n] instead.

```rust
    assert(s[0..2] == "AB", "Open-start slice: use 0..n, not ..n");
    assert(s[1..4] == "BCD", "Sub-string by byte range");
    assert(s[3..] == "DE", "Open-ended sub-string");
```

For UTF-8 strings, byte offsets snap to the nearest character boundary. Use a range to extract the portion from byte 2 up to (not including) the last byte.

```rust
    txt = "12😊🙃45";
    assert(txt[2..-1] == "😊🙃4", "UTF-8 sub-string by byte range");
```

=== Iterating Over Characters

Iterating over a string yields one character per UTF-8 code point. '#index' gives the byte offset of the start of the current character. '#next'  gives the byte offset immediately after the current character. For "Hi 😊!": H@0, i@1, ' '@2, '😊'@3..7, '!'@7..8

```rust
    result = "";
    positions = [];
    nexts = [];
    for c in "Hi 😊!" {
        positions += [c#index];
        nexts += [c#next];
        if c#index >= 3 {
            result += c;
        }
    }
    assert(result == "😊!", "Character iteration was {result}");
    assert("{positions}" == "[0,1,2,3,7]", "Character positions was {positions}");
    assert("{nexts}" == "[1,2,3,7,8]", "Character nexts was {nexts}");
```

=== Searching and Splitting

Standard string search functions (all offsets are byte-based).

```rust
    assert("something".starts_with("some"), "starts_with");
    assert("something".ends_with("thing"), "ends_with");
    assert("something".find("th") == 4, "find returns byte offset");
    assert("a longer text".contains("longer"), "contains");
```

trim() removes leading and trailing whitespace.

```rust
    assert(trim("  hello  ") == "hello", "trim");
}
```


= Integers

32-bit integers: arithmetic, conversions to/from text and float, bitwise operations, and null from division by zero.

```rust
fn main() {
```

Integer is the default type for any number, it is comparable with i32 in rust.

It is possible to convert numbers into texts and texts into numbers.

```rust
    v = 4;
    assert("{v}" == "4", "Convert numbers to text");
    assert("123" as integer == 123, "Convert text to number");
```

Priority rules determine the order of operators.

```rust
    assert(1 + 2 * 4 == 9, "Integer calculus");
    assert(1 + 2 << 2 == 12, "Binary shift");
    assert(0x0a8 & 15 == 8, "Binary and");
    assert(42 ^ 0b111111 == 21, "Binary xor");
    assert(105 % 100 == 5, "Modulus");
    assert(pow(2.0, 3.0) == 8.0, "Power");
```

The absolute value function is not a operation on numbers like `-1.abs()` in rust.

```rust
    assert(1 + abs(-2) == 3, "Absolute integer");
```

Division by zero results in a null (undefined) value that is equal to false in test.

```rust
    a = 2 * 2;
    a -= 4;
    assert(!(12 / a), "Null on division by zero");
```

```rust
    assert("a{12}b" == "a12b", "Formatting problem");
```

It is allowed to have full expressions inside a formatting block.

```rust
    assert("a{1 + 2 * 3:#x}b" == "a0x7b", "Hex formatting");
```

Hex literals must use lowercase digits. Uppercase hex digits (0xFF) are a parse error — always write 0xff.

```rust
    assert(0xff == 255, "Lowercase hex literal");
    assert(0x2a == 42, "Lowercase hex literal 2");
}
```


= Boolean

Boolean logic: 'and' 'or', bitwise '&' '|' '>>' '<<'', and 'null' as the absent/falsy value.

```rust
fn main() {
    assert(!(3 > 2 + 4), "Boolean test");
    assert(true as text == "true", "Convert boolean to text");
```

'and' / 'or' and their symbolic equivalents '&&' / '||' are interchangeable. Both forms use lazy evaluation: the right-hand side is only evaluated when the left-hand side alone does not determine the outcome.

```rust
    assert(1 > 0 and 2 > 1, "Both conditions true");
    assert(1 > 2 or 3 > 2, "Second condition true");
    assert(!(1 > 2 && 3 > 2), "First false, whole 'and' is false");
    assert(!(1 > 2 || 3 > 4), "Both false, whole 'or' is false");
```

Division by zero yields null, which is treated as false. Non-null values are treated as true.

```rust
    zero = 0;
    assert(!(12 / zero), "Null from division-by-zero is false");
    assert(12 > 0, "Positive integer is true");
```

Bitwise operations: '&' (and), '|' (or), '<<' / '>>' (shift). Note: '&' binds less tightly than comparisons, so parentheses are needed.

```rust
    assert((0x0f & 0xa8) == 8, "Bitwise and");
    assert((0xf0 | 0x0f) == 0xff, "Bitwise or");
    assert(1 << 4 == 16, "Left shift");
    assert(256 >> 3 == 32, "Right shift");
```

The '!' operator negates a boolean.

```rust
    assert(!false, "Not false is true");
    assert(!(1 > 2), "Not (false comparison) is true");
}
```


= Float

floating-point: arithmetic, math functions (sin, cos, log, round, ceil, floor), and format specifiers.

```rust
fn main() {
```

Float is a 64-bit floating-point number (equivalent to f64 in Rust). A literal with a decimal point is a float by default.

```rust
    assert(1.5 + 0.5 == 2.0, "Float addition");
    assert(3.0 / 2.0 == 1.5, "Float division");
    assert(2.0 * 1.5 == 3.0, "Float multiplication");
```

Use the 'f' suffix for single-precision (32-bit) floats.

```rust
    x = 0.1f + 2 * 1.0f;
    assert(x == 2.1f, "Single precision float");
```

Conversions between float, integer and text.

```rust
    assert(3 as float == 3.0, "Integer to float");
    assert("1.5" as float == 1.5, "Text to float");
    assert("{1.5}" == "1.5", "Float formatted as text");
```

Float formatting: '{value:width.precision}'. Width pads the whole number; precision controls decimal places.

```rust
    assert("{1.2:4.2}" == "1.20", "Float with width and precision");
    assert("{334.1:.2}" == "334.10", "Float with precision only");
    assert("{1.4:5}" == "  1.4", "Float with width only");
```

Math constants: PI is the ratio of a circle's circumference to its diameter.

```rust
    assert(round(PI * 1000.0) == 3142.0, "PI constant");
```

Exponentiation uses the pow(a, b) operator; log(x, base) computes the logarithm.

```rust
    assert(log(pow(4.0, 5), 2) == 10.0, "log base 2 of 4^5");
```

Trigonometric functions operate in radians. sin(PI) is near zero; cos(PI) is -1.

```rust
    assert(ceil(sin(PI) + cos(PI) * 1000) == -1000.0, "sin and cos");
```

abs() returns the absolute value.

```rust
    assert(abs(-2.5) == 2.5, "Absolute value of float");
```

round(), ceil(), floor() convert float to the nearest integer value.

```rust
    assert(round(2.6) == 3.0, "round up");
    assert(round(2.4) == 2.0, "round down");
    assert(ceil(2.1) == 3.0, "ceil");
    assert(floor(2.9) == 2.0, "floor");
}
```


= Functions

Functions: parameter defaults, in-out references with &, early return, and implicit return of the last expression.

=== Declaring Functions

A function is declared with 'fn', a parameter list, and an optional return type. The last expression in the body is the implicit return value.

```rust
fn greet(name: text, greeting: text = "Hello") -> text {
    greeting + ", " + name + "!"
}
```

=== Reference Parameters and Defaults

Functions with no return type perform side effects only. Reference parameters (prefixed with '&') let the function modify the caller's variable. Default values are specified with '= value' after the type.

```rust
fn add(a: &integer, b: integer, c: integer = 0) {
    a += b + c;
}
```

=== Early Return

A function can return early with an explicit 'return' statement.

```rust
fn classify(n: integer) -> text {
    if n < 0 { return "negative"; }
    if n == 0 { return "zero"; }
    "positive"
}
```

=== Const and Reference Parameters

A 'const' parameter guarantees the function will never change its value. This is a compile-time check: attempting to assign to a 'const' parameter is an error. A '&' parameter passes by reference so the function *can* change the caller's variable. Passing something by '&' when you never actually change it is also a compile error — use a plain value parameter instead.

```rust
fn scale(a: const integer, factor: const integer) -> integer {
    a * factor
}
```

=== Type-Based Dispatch

```rust
fn describe_int(v: integer) -> text { "integer:{v}" }
fn describe_text(v: text) -> text { "text:{v}" }
```

```rust
fn main() {
```

Calling a function with all arguments.

```rust
    assert(greet("World", "Hi") == "Hi, World!", "Explicit argument");
```

Calling with the default value for 'greeting'.

```rust
    assert(greet("World") == "Hello, World!", "Default argument");
```

Reference parameters allow the function to modify the caller's variable.

```rust
    v = 1;
    add(v, 2);       // v = 1 + 2 = 3
    add(v, 4, 1);    // v = 3 + 4 + 1 = 8
    assert(v == 8, "Reference parameter: {v}");
```

Early return example.

```rust
    assert(classify(-5) == "negative", "Classify negative");
    assert(classify(0) == "zero", "Classify zero");
    assert(classify(3) == "positive", "Classify positive");
```

'const' parameters cannot be modified; they are checked at compile time.

```rust
    assert(scale(3, 7) == 21, "scale(3,7)");
```

Functions with different names handle different types.

```rust
    assert(describe_int(42) == "integer:42", "Integer describe");
    assert(describe_text("hi") == "text:hi", "Text describe");
}
```


= Vector

Dynamic arrays: literals, slices, removal, reverse iteration, and for-loops embedded in format strings.

```rust
fn main() {
```

A vector literal is written with square brackets. '#first' is true for the first element; '#index' gives the position.

```rust
    x = [1, 3, 6, 9];
    b = "";
    for v in x {
        if !v#first {
            b += " ";
        }
        b += "{v#index}:{v}"
    }
    assert(b == "0:1 1:3 2:6 3:9", "result {b}");
```

Append another vector with '+='. Then remove elements while iterating using 'v#remove' inside a filtered loop.

```rust
    x += [12, 14, 15];
    for v in x if v % 3 != 0 {
        v#remove;
    }
    assert("{x}" == "[3,6,9,12,15]", "result {x}");
```

A range index extracts a sub-vector; the upper bound is exclusive. Omitting the upper bound goes to the end of the vector.

```rust
    pows = [1, 2, 4, 8, 16];
    assert("{pows[1..3]}" == "[2,4]", "Sub-vector");
    assert("{pows[3..]}" == "[8,16]", "Open-ended sub-vector");
```

Accessing an index outside the vector's bounds returns null.

```rust
    assert(!pows[10], "Out-of-bounds access returns null");
```

A for loop can be written directly inside a format string. An optional format specifier after ':' applies to every element.

```rust
    assert("{for n in 1..7 {n*2}:02}" == "[02,04,06,08,10,12]", "Formatted vector loop");
```

Reverse iteration uses rev() on the range.

```rust
    c = 0;
    for e in pows[rev(0..=3)] {
        c = c * 10 + e;
    }
    assert(c == 8421, "Reverse sub-vector iteration");
```

A vector of structs can be created with a repeated element using '; count'. (See 08-struct.loft for struct syntax.)

Limitation: appending to a vector inside a '&' reference function (v += [item]) does NOT propagate back to the caller. Only field-level mutations (v[i].field = x) are visible after the call. To return a larger vector, use a return value instead: fn with_extra(v: vector<integer>, x: integer) -> vector<integer> { v += [x]; v } items = with_extra(items, 99);

```rust
}
```


= Structs

Record types: field constraints, computed fields using $, methods, JSON and pretty-print formatting.

```rust
struct Area {
    height: u16,
    terrain: u8,
    water: u8,
    direction: u8
}
```

=== Field Constraints

'limit(min, max)' constrains an integer field to a range. 'not null' makes zero a valid stored value instead of the null sentinel. Fields omitted in a constructor default to zero (or null for nullable fields).

```rust
struct Point {
    r: integer limit(0, 255) not null,
    g: integer limit(0, 255) not null,
    b: integer limit(0, 255) not null
}
```

=== Methods

A method is a function whose first parameter is named 'self' with the struct type. It is called with dot notation: value.method().

```rust
fn value(self: Point) -> integer {
    self.r * 0x10000 + self.g * 0x100 + self.b
}
```

=== Computed Fields

'default(expr)' and 'virtual(expr)' compute a field value from other fields. '$' refers to the struct being initialised.

```rust
struct Object {
    name_length: integer = len($.name),
    name: text
}
```

```rust
fn main() {
```

A vector of structs can be initialised with a repeated element using '; count'.

```rust
    map = [Area {height:0, terrain:1, water:1, direction:1}; 16 ];
    assert("{map[3]}" == "{{height:0,terrain:1,water:1,direction:1}}", "record {map[3]}");
```

Fields not mentioned in the constructor receive their zero/null default.

```rust
    p = Point { r:128, b:128 };
    assert(p.g == 0, "Omitted field defaults to zero");
    assert("{p}" == "{{r:128,g:0,b:128}}", "Struct compact formatting");
```

The ':# ' format specifier produces pretty-printed output with newlines. The ':j' specifier produces JSON.

```rust
    o = Object { name: "hello" };
    assert(o.name_length == 5, "Calculated field");
    assert("{o:j}" == "{{\"name_length\":5,\"name\":\"hello\"}}", "JSON format");
```

Methods are called with dot notation; the result can be formatted inline.

```rust
    purple = Point { r:128, b:128 };
    assert("{purple.value():x}" == "800080", "Method result in format");
```

Limitation: do not call a method directly on a constructor expression. The parser rejects 'MyStruct { ... }.method()' — assign to a variable first: tmp = Point { r: 1, g: 2, b: 3 }; result = tmp.value();

Limitation: methods that return a new struct record (-> MyStruct) currently crash at runtime. Methods that return scalars (integer, float, text) or modify 'self' in place work correctly.

```rust
}
```

defaults on fields & null defaults


= Enums

Enums: plain value enums with ordering and text conversion; struct enums with field access and polymorphic dispatch.

Enum values can be compared, ordered, and converted to/from integer and text.

```rust
enum Direction { North, East, South, West }
```

=== Struct Enums

An enum variant can carry data as named fields, making it a 'struct enum'. Each variant is its own type and can have its own methods.

```rust
enum Shape {
    Circle { radius: float },
    Rect { width: float, height: float }
}
```

=== Polymorphic Dispatch

Polymorphic dispatch: define the same function name for each variant. The call site picks the right version based on the runtime type.

```rust
fn area(self: Circle) -> float {
    PI * pow(self.radius, 2)
}
```

```rust
fn area(self: Rect) -> float {
    self.width * self.height
}
```

```rust
fn main() {
```

Plain enum: comparison and ordering (by declaration order).

```rust
    d = East;
    assert(d == East, "Enum equality");
    assert(d != North, "Enum inequality");
    assert(d > North, "East declared after North, so it is greater");
    assert(West > South, "West declared last, so it is greatest");
```

Convert text to an enum value.

```rust
    assert("West" as Direction == West, "Text to enum");
```

Struct-enum variants are constructed like structs. Access their fields with dot notation.

```rust
    c = Circle { radius: 1.0 };
    assert(c.radius == 1.0, "Variant field access");
```

```rust
    r = Rect { width: 4.0, height: 5.0 };
    assert(r.width * r.height == 20.0, "Rect area manually");
```

Polymorphic dispatch: the correct 'area' function is chosen by variant type.

```rust
    assert(round(c.area() * 1000) == round(PI * 1000), "Circle area = PI*r^2");
    assert(r.area() == 20.0, "Rect area = width*height");
```

Plain enums can be formatted to their variant name.

```rust
    assert("{d}" == "East", "Format plain enum");
```

Limitation: polymorphic methods that return text and use format strings to access fields ('fn describe(self: Circle) -> text { "r={self.radius}" }') cause a runtime crash when defined on multiple struct-enum variants. Workaround: return a scalar value and build the text in the caller, or use a single non-polymorphic function that dispatches on the enum variant.

```rust
}
```


= Sorted

"sorted<T[key]>: O(log n) key lookup and in-order iteration in a sorted binary tree; ascending and descending sort keys.

A 'sorted' field keeps records in a sorted binary tree that can be traversed in key order and looked up by key in O(log n) time. Key fields are listed in brackets: '-field' sorts descending, 'field' ascending.

```rust
struct Elm { key: text, value: integer }
struct Db { map: sorted<Elm[-key]> }
```

```rust
fn main() {
```

Populate a sorted collection; the collection maintains its order automatically.

```rust
    db = Db { map: [
        Elm { key: "One",   value: 1 },
        Elm { key: "Two",   value: 2 },
        Elm { key: "Three", value: 3 },
        Elm { key: "Four",  value: 4 }
    ]};
```

Look up an element by its sort key using index syntax. Returns null if the key is not present.

```rust
    assert(db.map["Two"].value == 2, "Key lookup: Two");
    assert(db.map["Three"].value == 3, "Key lookup: Three");
    assert(!db.map["Five"], "Missing key returns null");
    assert(!db.map[null], "Null key returns null");
```

New elements can be appended; they are inserted in the right position.

```rust
    db.map += [Elm { key: "Zero", value: 0 }];
    assert(db.map["Zero"].value == 0, "Newly added element");
```

Iterating visits elements in sorted order. With '-key' (descending text), the order is: Zero, Two, Three, One, Four.

```rust
    sum = 0;
    for v in db.map {
        sum = sum * 10 + v.value;
    }
```

Zero(0), Two(2), Three(3), One(1), Four(4) → 0*10+2=2, *10+3=23, *10+1=231, *10+4=2314

```rust
    assert(sum == 2314, "Sorted iteration total: {sum}");
```

Limitation: reverse iteration over a sorted collection (for v in rev(db.map)) is not yet implemented. To iterate in the opposite order, collect elements into a plain vector first and use rev() on that: items = []; for v in db.map { items += [v]; } for v in items[rev(0..=len(items)-1)] { ... }

```rust
}
```

filling and finding values


= Index

index<T[key]>: balanced red-black tree with strict sorted order, multi-key lookup, and range iteration.

An 'index' stores records in a balanced red-black tree, maintaining strict sorted order and supporting O(log n) lookup and range iteration. Unlike 'sorted', an index embeds the tree pointers inside each record itself, so each element can belong to only one index at a time. Key fields are listed in brackets: 'field' ascending, '-field' descending.

```rust
struct Elm { nr: integer, key: text, value: integer }
struct Db { map: index<Elm[nr, -key]> }
```

```rust
fn main() {
```

Populate the index; elements are sorted by (nr ascending, key descending).

```rust
    db = Db { map: [
        Elm { nr: 101, key: "One",   value: 1 },
        Elm { nr: 92,  key: "Two",   value: 2 },
        Elm { nr: 83,  key: "Three", value: 3 },
        Elm { nr: 83,  key: "Four",  value: 4 },
        Elm { nr: 83,  key: "Five",  value: 5 },
        Elm { nr: 63,  key: "Six",   value: 6 },
    ]};
```

Look up an element by its full key tuple; returns null for missing keys.

```rust
    assert(db.map[101, "One"].value == 1, "Key lookup");
    assert(!db.map[12, ""], "Missing key returns null");
    assert(!db.map[83, "One"], "Wrong secondary key returns null");
```

Iterate all elements in key order (nr asc, key desc).

```rust
    total = 0;
    for r in db.map {
        total += r.value;
    }
    assert(total == 21, "Sum of all values: {total}");
```

Range iteration: visit elements whose key falls between two bounds. The range [83..92, "Two"] visits elements with 83 <= nr < 92 and key <= "Two" (in descending key order, "Two" is the lower bound).

```rust
    sum = 0;
    for v in db.map[83..92, "Two"] {
        sum = sum * 10 + v.value;
    }
```

Elements in range: (83,Three,3), (83,Four,4), (83,Five,5)

```rust
    assert(sum == 345, "Range iteration result: {sum}");
}
```


= Hash

hash<T[key]>: O(1) average-time key lookup; combining a hash with a vector for ordered traversal and fast access.

A 'hash' field provides O(1) average-time lookup by one or more key fields. The key fields are listed in brackets: 'hash<Type[field1, field2]>'. A hash is not ordered; for ordered access combine it with a 'sorted' or 'vector' field.

```rust
struct Keyword { name: text }
struct Data { h: hash<Keyword[name]> }
```

A hash backed by a vector allows fast key lookup while the vector maintains insertion order.

```rust
struct Count { t: text, v: integer }
struct Counting {
    entries: vector<Count>,
    lookup:  hash<Count[t]>
}
```

```rust
fn fill(c: Counting) {
    c.entries = [
        { t: "One",   v: 1 },
        { t: "Two",   v: 2 },
        { t: "Three", v: 3 },
        { t: "Four",  v: 4 }
    ]
}
```

```rust
fn main() {
```

Populate a hash; lookup uses index syntax with the key value(s).

```rust
    d = Data {};
    d.h = [{ name: "one" }, { name: "two" }];
    d.h += [{ name: "three" }, { name: "four" }];
```

Found elements are truthy; a missing key returns null (falsy).

```rust
    assert(d.h["three"], "Key exists");
    assert(!d.h["None"], "Missing key returns null");
```

Combining a vector and a hash on the same records gives ordered traversal (via the vector) and O(1) key-based access (via the hash).

```rust
    c = Counting {};
    fill(c);
    assert(c.lookup["Three"].v == 3, "Hash lookup: Three");
    assert(c.lookup["One"].v == 1, "Hash lookup: One");
    assert(!c.lookup["Five"], "Missing key returns null");
```

Iterate the vector in insertion order while using the hash for lookups.

```rust
    add = 0;
    for item in c.entries {
        add += item.v;
    }
    assert(add == 10, "Sum via vector iteration: {add}");
}
```


= File

Files are opened lazily: file(path) creates a handle; the OS file opens on the first read or write and closes when the handle goes out of scope.

'file(path)' creates a File handle. 'f#format' returns the format of the file: TextFile, LittleEndian, BigEndian, Directory, or NotExists. 'lines()' reads a text file and returns it as a vector of lines.

Clean up any leftover files from a previous interrupted run.

```rust
fn cleanup() {
    delete("test.bin");
    delete("test2.bin");
    delete("buffer.bin");
}
```

```rust
struct Buffer {
   size: i32,
   data: vector<single>
}
```

```rust
fn main() {
    cleanup();
```

--- Directory and text reading --- 'file("example")' returns a handle whose format is Directory. 'lines()' reads the file at 'example/config/terrain.txt' and splits it into lines.

```rust
    ex = file("example");
    assert(ex#format == Directory, "example is a directory");
    c = file("example/config/terrain.txt").lines();
    assert(c[1] == "    terrain = [", "Line was '{c[1]}'");
```

--- exists() and delete() --- 'exists(path)' is shorthand for file(path)#format != NotExists. 'delete()' returns false when the file does not exist.

```rust
    assert(!exists("test.bin"), "File should not exist before the test.");
    assert(!delete("nonexistent_xyz.bin"), "delete on missing file returns false");
```

--- Binary write --- Set f#format before writing: LittleEndian or BigEndian. f += value writes the value's bytes to the file. Supported scalar types: u8, u16, i32, long, single, float, text. Limitation: f += vector<T> is not yet implemented (writes 0 bytes). Write individual elements with a loop: for v in vec { f += v; }

```rust
    { f = file("test.bin");
      assert(f#format == NotExists, "File should not exist yet.");
      f#format = BigEndian;
      f += 0 as u8;
      f += 1 as u8;
      f += 0x203 as u16;
      f += 0x4050607;
      f += 0x8090a0b0c0d0e0fl;
```

'f#size' returns the total number of bytes written so far.

```rust
      assert(f#size == 16l, "Should have written 16 bytes.");
```

Text is written as raw UTF-8 bytes with no length prefix.

```rust
      f += "Hello world!";
      assert(f#size == 28l, "Size should be 28 bytes (16 + 12).");
    } // The file closes when the handle goes out of scope.
```

```rust
    assert(exists("test.bin"), "File should exist after writing.");
```

move(src, dst) refuses if dst exists, or if either path leaves the project directory.

```rust
    assert(!move("test.bin", "../test.bin"), "Should refuse to move outside the project.");
    assert(move("test.bin", "test2.bin"), "Could not move the file.");
```

--- Binary read --- Open a file for reading; the default format is TextFile. Set f#format to the format used when writing before reading.

```rust
    { f = file("test2.bin");
      assert(f#format == TextFile, "The default format is TextFile.");
      f#format = LittleEndian;
```

f#read(n) as T reads n bytes and interprets them as type T. f#index is the byte offset where the last read started. f#next is the current byte position (start of the next read).

```rust
      v = f#read(4) as i32;
      assert(v == 0x3020100, "BigEndian bytes 0..3 read as LittleEndian i32.");
      assert(f#index == 0l, "Last read started at byte 0.");
      assert(f#next == 4l, "Next read starts at byte 4.");
```

f#next = pos seeks to an arbitrary byte position.

```rust
      f#next = 16l;
      s = f#read(5) as text;
      assert(s == "Hello", "Partial text read from offset 16.");
      assert(f#index == 16l, "Last read started at byte 16.");
      assert(f#next == 21l, "Next position after 5-byte text read.");
```

Reading past EOF returns whatever bytes are available.

```rust
      rest = f#read(100) as text;
      assert(rest == " world!", "Read continues to end of file.");
      assert(f#next == f#size, "Position should be at end of file.");
```

Seek back to start and re-read the first integer.

```rust
      f#next = 0l;
      assert(f#read(4) as i32 == 0x3020100, "Seek-and-reread matches original.");
    }
    assert(delete("test2.bin"), "Could not remove the test file.");
```

--- Writing individual elements and reading into a struct --- Write a count and then the floats one by one. sizeof(T) returns the byte size of a type; use it to compute the read length.

```rust
    { buf = file("buffer.bin");
      buf#format = LittleEndian;
      buf += 4 as i32;
      buf += 1.1f;
      buf += 1.2f;
      buf += 2.1f;
      buf += 2.2f;
    }
```

Read the binary data back into a struct field.

```rust
    { b = Buffer {};
      f = file("buffer.bin");
      f#format = LittleEndian;
      n = f#read(4) as i32;
      b.data = f#read(n * sizeof(single));
    }
    assert(delete("buffer.bin"), "Could not remove buffer.bin.");
}
```


= Image

Image loading and pixel-level manipulation using the built-in Image type.

```rust
fn main() {
}
```


= Lexer

Lexer library: tokenising source text, handling multi-character operators, comments, string literals, and formatting expressions.

Before parsing, register the multi-character tokens and reserved keywords for your language.

`set_tokens` ensures operators like `+=` or `>>` are scanned as one token instead of two.

`set_keywords` prevents reserved words from being returned by `identifier()`.

```rust
use lexer;
```

```rust
fn main() {
    l = lexer::Lexer {};
    l.set_tokens(["+=", "*=", "-=", "<=", ">=", "!=", "==", ">>", "<<", "->", "=>", ">>>", "..", "..=", "&&", "||"]);
    l.set_keywords(["for", "in", "if", "else", "fn", "pub", "use", "struct", "enum", "match", "and", "or"]);
```

`parse_string` feeds source text into the lexer.

`int()` consumes and returns the next integer token, or null if the current token is not an integer.

`matches()` consumes a token only when it equals the given string; `peek()` returns it without consuming.

`long_int()` reads a long integer (suffixed with `l`). `position()` returns `file:line:col`.

```rust
    l.parse_string("Tokens", "12 += -2 * 3l >> 4");
    assert(l.int() == 12, "Integer");
    assert(!l.matches("+"), "Incorrect plus");
    assert(l.peek() != "+", "Incorrect plus");
    assert(l.matches("+="), "Incorrect plus_is");
    assert(l.int() == -2, "Second integer");
    assert(l.matches("*"), "Incorrect multiply");
    assert(l.int() != 3, "Third number");
    assert(l.long_int() == 3, "Incorrect long");
    assert(l.position() == "Tokens:1:15", "Incorrect position {l.position()}");
    assert(!l.matches(">"), "Incorrect higher");
    assert(l.matches(">>"), "Incorrect logical shift");
    assert(l.position() == "Tokens:1:18", "Incorrect position {l.position()}");
```

`constant_text()` reads and unescapes a quoted string literal.

`constant_character()` reads a quoted character literal.

```rust
    l.parse_string("Texts", "\"123\" + '4'");
    assert(l.constant_text() == "123", "Incorrect text literal");
    assert(l.matches("+"), "Incorrect add");
    assert(l.constant_character() == "123", "Incorrect text literal");
```

Comments are collected automatically during scanning.

`last_comment()` returns accumulated comment text since the last consumed token.

`comment_behind()` is true when the comment appeared on the same line as preceding code.

Multiple consecutive comment lines are joined with newlines into one string.

`is_finished()` returns true once all input has been consumed.

```rust
    l.parse_string("Comments", "// starting comments\n123 // same line comment\n// extra comment\n4");
    assert(!l.comment_behind(), "Initial comment not behind");
    assert(l.last_comment() == "starting comments", "Initial comment");
    assert(l.int() == 123, "Content integer");
    assert(l.comment_behind(), "Second comment is behind");
    assert(l.last_comment() == "same line comment\nextra comment", "Second comment");
    assert(!l.is_finished(), "Not Ready");
    assert(l.int() == 4, "Second integer");
    assert(l.last_comment() == "", "No remaining comment");
    assert(l.is_finished(), "Ready");
```

String literals may embed expressions with `{expr}`.

When the lexer reaches `{`, `constant_text()` returns the literal part before it and `is_formatting()` becomes true. Parse the embedded expression normally after calling `set_formatting(false)`, then call `set_formatting(true)` before consuming the closing `}}`. `constant_text()` then continues with the next literal segment.

```rust
    l.parse_string("Formatting", "\"abc{{12 + 34}}def\"");
    assert(l.constant_text() == "abc", "Before formatting");
    assert(l.is_formatting(), "Formatting");
    l.set_formatting(false);
    assert(l.int() == 12, "First integer");
    assert(l.matches("+"), "Incorrect plus");
    assert(l.int() == 34, "Second integer");
    l.set_formatting(true);
    assert(l.matches("}}"), "Incorrect closing brace");
    assert(l.constant_text() == "def", "After formatting");
    assert(!l.is_formatting(), "Formatting");
}
```


= Parser

Parser library: parsing loft source code programmatically from within a loft program.

`parse(name, source)` is the single entry point. It takes a display name (used in error messages) and a loft source string. The name argument does not need to correspond to a real file; it is only used when reporting parse errors.

The parser understands the full loft grammar:

- `struct Name { field: type \[= default\] }` — named-field aggregates
- `enum Name { Variant \[{ field: type }\] }` — tagged unions with optional payload
- `fn name(params) \[-> type\] { body }` — functions with a block body
- `fn name(params) \[-> type\]; \#rust "template"` — operator templates backed by Rust
- `use module;` — module imports
- Expressions: binary operators with precedence, function calls, field access,

index expressions, if/else, for loops, blocks, and formatted string literals

- Type expressions: plain names, generic types like `vector<T>`, sorted/hash/index

collections with key fields, and integer ranges with `limit(min, max)`

```rust
use parser;
```

```rust
fn main() {
```

Parse a minimal function definition. The double braces `{{` and `}}` are the loft way to write literal braces inside a format string.

```rust
    parser::parse("hello", "fn main() {{ println(\"Hello World\"); }}");
```

Parse a struct definition followed by a function that references it. The parser validates the syntax but does not execute the code.

```rust
    parser::parse("point", "struct Point {{ x: integer, y: integer }} fn origin() -> Point {{ Point {{ x: 0, y: 0 }} }}");
```

Parse an enum with a plain variant and a variant carrying fields.

```rust
    parser::parse("shape", "enum Shape {{ Circle {{ radius: float }}, Rectangle {{ w: float, h: float }} }}");
}
```


= Libraries

Libraries let you split code across files. A library is any `.loft` file placed in a `lib/` directory. Use `use name;` to import it, then access its definitions as `name::Thing`.

`use` statements must appear at the very top of the file, before any function or struct definitions. Placing a `use` after a definition is a syntax error.

```rust
use testlib;
```

--- Constants --- Library constants are accessed with the `libname::CONSTANT` prefix.

--- Enums --- Library enum variants are also accessed with the prefix.

--- Struct construction --- All library types must be constructed with their namespace prefix. Writing `Point {}` without the prefix is a parse error.

```rust
fn main() {
```

Constants from a library require the library prefix.

```rust
    assert(testlib::MAX_SIZE == 100, "library constant MAX_SIZE");
    assert(testlib::MIN_SIZE == 1, "library constant MIN_SIZE");
```

Library enum variants: comparison and ordering work as normal.

```rust
    s = testlib::Ok;
    assert(s == testlib::Ok, "enum equality");
    assert(s < testlib::Error, "enum ordering");
    assert("{s}" == "Ok", "enum to text: {s}");
    assert("Warning" as testlib::Status == testlib::Warning, "text to enum");
```

Library enum values can be passed to library free functions.

```rust
    assert(testlib::status_text(testlib::Error) == "err", "free fn with enum arg");
```

Structs are constructed with namespace prefix and accessed by field.

```rust
    p = testlib::Point { x: 3.0, y: 4.0 };
    assert(p.x == 3.0, "field access: x={p.x}");
    assert(p.y == 4.0, "field access: y={p.y}");
```

Methods defined in the library are called without a prefix.

```rust
    dist = p.distance();
    assert(round(dist) == 5.0, "method call: distance={dist}");
```

Scalar fields can be mutated directly.

```rust
    b = testlib::Bag { label: "test", count: 0 };
    b.label = "updated";
    assert(b.label == "updated", "direct scalar field mutation");
```

Methods that mutate scalar fields work.

```rust
    b.bump();
    assert(b.count == 1, "method scalar mutation: count={b.count}");
    b.bump();
    assert(b.count == 2, "method scalar mutation: count={b.count}");
```

Free functions: called with the library prefix.

```rust
    assert(testlib::add(3, 4) == 7, "free function add");
    assert(testlib::add(0, -5) == -5, "free function negative");
```

Library types can be used as function parameter types (by their full name). Passing them to locally-defined functions works as long as the parameter type is written as the plain struct name (not with :: prefix — see limitation below).

Library struct with vector field: initialization via struct literal works.

```rust
    bag2 = testlib::Bag { label: "full", count: 3, items: [
        testlib::Point { x: 1.0, y: 0.0 },
        testlib::Point { x: 0.0, y: 1.0 }
    ]};
    assert(len(bag2.items) == 2, "initialized vector field: {len(bag2.items)}");
    assert(bag2.items[0].x == 1.0, "vector field element access");
```

Duplicate `use` of the same library is silently ignored (no error). Multiple libraries can be imported in one file. Libraries can themselves use other libraries (nested use).

--- Limitations ---

Limitation 1: `use` must appear before all definitions. The following would be a fatal syntax error: fn foo() {} use testlib;   // ERROR: Syntax error

Limitation 2: Unqualified access to library names is not supported. `Point {}` without prefix → parse error ("Expect token ;") `MAX_SIZE` without prefix → unknown variable `add(1, 2)` without prefix → unknown function

Limitation 3: You cannot write a method that takes a library type as `self` in the importing file. The `::` namespace separator is not allowed in function parameter type positions: fn extend(self: testlib::Point) -> float { ... }   // ERROR: Syntax error Workaround: define all methods that operate on a library type inside the library.

Limitation 4: `pub` on struct fields is not supported and causes a parse error. `pub` on top-level `struct` and `fn` definitions is accepted but has no effect (there is no visibility system — all library definitions are always accessible).

Limitation 5: Appending to a scalar vector field with `+=` on an existing struct variable does not persist. Use struct literal initialization instead: b.items += p   // has no visible effect bag2 = Bag { items: [p1, p2] }   // works Struct vector fields (vector<MyStruct>) can be appended with `+= [elem]`.

Limitation 6: You cannot add methods to a library type from an importing file. `self:` parameters do not accept the `::` namespace separator: fn extend(self: testlib::Point) -> float { ... }   // ERROR: Syntax error fn extend(self: Point) -> float { ... }            // ERROR: Undefined type Workaround: add all methods inside the library file itself. Regular (non-self) parameters do accept `libname::Type`: fn check(p: testlib::Point) -> boolean { ... }    // works

```rust
}
```


= Standard Library

== Types

Primitive types built into lav.

```rust
pub type boolean size(1)
```

True or false value.

```rust
pub type integer size(4)
```

32-bit signed integer.

```rust
pub type long size(8)
```

64-bit signed integer. Use when values exceed ~2 billion.

```rust
pub type single size(4)
```

32-bit floating-point. Good for graphics and performance-sensitive math.

```rust
pub type float size(8)
```

64-bit floating-point. Use when precision matters.

```rust
pub type text size(4)
```

UTF-8 string.

```rust
pub type character size(4)
```

A single Unicode code point.

```rust
pub type u8=integer limit(0, 255) size(1)
```

Integer subtypes for compact storage in struct fields. Behave as integer in expressions. 0 – 255, 1 byte.

```rust
pub type i8=integer limit(-128, 127) size(1)
```

-128 – 127, 1 byte.

```rust
pub type u16=integer limit(0, 65535) size(2)
```

0 – 65535, 2 bytes.

```rust
pub type i16=integer limit(-32768, 32767) size(2)
```

-32768 – 32767, 2 bytes.

```rust
pub type i32=integer size(4)
```

Full 32-bit integer range, 4 bytes.

== Math

Functions for numeric computation. All trigonometric functions work in radians. Both single and float variants exist for every function — choose single for speed, float for precision.

```rust
pub fn abs(both: integer) -> integer
```

Absolute value. Removes the sign from a negative integer.

```rust
pub fn abs(both: long) -> long
```

Absolute value for long integers.

```rust
pub fn abs(both: single) -> single
```

Absolute value for single-precision floats.

```rust
pub fn cos(both: single) -> single
```

Cosine. Use for circular motion: x = r * cos(angle).

```rust
pub fn sin(both: single) -> single
```

Sine. Use for circular motion: y = r * sin(angle).

```rust
pub fn tan(both: single) -> single
```

Tangent. Use for slopes and perspective projection.

```rust
pub fn acos(both: single) -> single
```

Arc cosine. Returns the angle (in radians) whose cosine is v.

```rust
pub fn asin(both: single) -> single
```

Arc sine. Returns the angle whose sine is v.

```rust
pub fn atan(both: single) -> single
```

Arc tangent of a single value. Returns angle in (-PI/2, PI/2).

```rust
pub fn atan2(both: single, v2: single) -> single
```

Arc tangent of y/x, preserving the correct quadrant. Use instead of atan when you have separate x/y components.

```rust
pub fn ceil(both: single) -> single
```

Round up to the nearest integer value. Use to compute required buffer sizes from fractional counts.

```rust
pub fn floor(both: single) -> single
```

Round down to the nearest integer value. Use to convert a float position to a tile index.

```rust
pub fn round(both: single) -> single
```

Round to the nearest integer value (half rounds away from zero).

```rust
pub fn sqrt(both: single) -> single
```

Square root. Use for distances and normalization.

```rust
pub fn log(both: single, v2: single) -> single
```

Logarithm of v in the given base. Use for converting between scales (e.g., decibels).

```rust
pub fn pow(both: single, v2: single) -> single
```

Raises base to the power exp. Use for exponential growth curves and scaling.

```rust
pub fn abs(both: float) -> float
```

Absolute value for double-precision floats.

```rust
pub PI = OpMathPiFloat()
```

The ratio of a circle's circumference to its diameter (3.14159...).

```rust
pub E = OpMathEFloat()
```

Euler's number, the base of natural logarithms (2.71828...).

```rust
pub fn cos(both: float) -> float
```

Cosine. Use for circular motion: x = r * cos(angle).

```rust
pub fn sin(both: float) -> float
```

Sine. Use for circular motion: y = r * sin(angle).

```rust
pub fn tan(both: float) -> float
```

Tangent. Use for slopes and perspective projection.

```rust
pub fn acos(both: float) -> float
```

Arc cosine. Returns the angle (in radians) whose cosine is v.

```rust
pub fn asin(both: float) -> float
```

Arc sine. Returns the angle whose sine is v.

```rust
pub fn atan(both: float) -> float
```

Arc tangent of a single value. Returns angle in (-PI/2, PI/2).

```rust
pub fn atan2(both: float, v2: float) -> float
```

Arc tangent of y/x, preserving the correct quadrant. Use instead of atan when you have separate x/y components.

```rust
pub fn ceil(both: float) -> float
```

Round up to the nearest integer value. Use to compute required buffer sizes from fractional counts.

```rust
pub fn floor(both: float) -> float
```

Round down to the nearest integer value. Use to convert a float position to a tile index.

```rust
pub fn round(both: float) -> float
```

Round to the nearest integer value (half rounds away from zero).

```rust
pub fn sqrt(both: float) -> float
```

Square root. Use for distances and normalization.

```rust
pub fn log(both: float, v2: float) -> float
```

Logarithm of v in the given base. Use for converting between scales (e.g., decibels).

```rust
pub fn pow(both: float, v2: float) -> float
```

Raises base to the power exp. Use for exponential growth curves and scaling.

== Text

Functions for working with text (UTF-8 strings) and character values.

```rust
pub fn len(both: text) -> integer
```

Number of bytes in the text. Use for bounds checks and iteration limits.

```rust
pub fn len(both: character) -> integer
```

Byte length of the character's UTF-8 encoding (1–4).

Functions for searching, transforming, and classifying text and character values. Character classification functions return true only if every character in the text satisfies the condition. The single-character variants test one code point.

```rust
pub fn starts_with(self: text, value: text) -> boolean
```

Returns true if self begins with value. Use for prefix matching (e.g., protocol detection).

```rust
pub fn ends_with(self: text, value: text) -> boolean
```

Returns true if self ends with value. Use for suffix matching (e.g., file extension checks).

```rust
pub fn trim(both: text) -> text[both]
```

Removes leading and trailing whitespace. Use when processing user input or file content.

```rust
pub fn trim_start(self: text) -> text[self]
```

Removes leading whitespace only.

```rust
pub fn trim_end(self: text) -> text[self]
```

Removes trailing whitespace only.

```rust
pub fn find(self: text, value: text) -> integer
```

Returns the byte index of the first occurrence of value, or null if not found. Use to locate substrings before slicing.

```rust
pub fn rfind(self: text, value: text) -> integer
```

Returns the byte index of the last occurrence of value, or null if not found. Use to find file extensions or the last path separator.

```rust
pub fn contains(self: text, value: text) -> boolean
```

Returns true if value appears anywhere in self. Simpler than find when you only need a yes/no answer.

```rust
pub fn replace(self: text, value: text, with: text) -> text
```

Returns a copy of self with every occurrence of value replaced by with.

```rust
pub fn to_lowercase(self: text) -> text
```

Returns a lowercase copy. Use for case-insensitive comparisons.

```rust
pub fn to_uppercase(self: text) -> text
```

Returns an uppercase copy.

```rust
pub fn is_lowercase(self: text) -> boolean
```

True if all characters are lowercase letters.

```rust
pub fn is_lowercase(self: character) -> boolean
```

True if the character is a lowercase letter.

```rust
pub fn is_uppercase(self: text) -> boolean
```

True if all characters are uppercase letters.

```rust
pub fn is_uppercase(self: character) -> boolean
```

True if the character is an uppercase letter.

```rust
pub fn is_numeric(self: text) -> boolean
```

True if all characters are numeric digits (Unicode numeric, not just ASCII 0–9).

```rust
pub fn is_numeric(self: character) -> boolean
```

True if the character is a numeric digit.

```rust
pub fn is_alphanumeric(self: text) -> boolean
```

True if all characters are letters or digits. Use to validate identifiers or tokens.

```rust
pub fn is_alphanumeric(self: character) -> boolean
```

True if the character is a letter or digit.

```rust
pub fn is_alphabetic(self: text) -> boolean
```

True if all characters are alphabetic.

```rust
pub fn is_alphabetic(self: character) -> boolean
```

True if the character is alphabetic.

```rust
pub fn is_whitespace(self: text) -> boolean
```

True if all characters are whitespace. Use to detect blank lines.

```rust
pub fn is_control(self: text) -> boolean
```

True if all characters are control characters.

== Collections

Operations on vector<T> — the primary ordered collection type. Vectors are grown by appending with += and elements are accessed by index.

```rust
pub fn len(both: vector) -> integer
```

Number of elements in the vector. Use in loop bounds: for i in 0..v.len().

== Output and Diagnostics

```rust
pub fn assert(test: boolean, message: text)
```

Panics with message if test is false. Use to verify invariants during development.

```rust
pub fn panic(message: text)
```

Immediately terminates execution with message. Use for unrecoverable error states.

```rust
pub fn print(v1: text)
```

Writes v to standard output without a newline. Use for progress output and building up a line incrementally.

```rust
pub fn println(v1: text)
```

Writes v followed by a newline. The standard choice for line-oriented output.

== File System

Types and functions for reading and writing files. A File value is obtained via file() and carries the path, format, and an internal reference.

```rust
pub struct EnvVariable {
    name: text,
    value: text
}
```

An environment variable as a name/value pair.

```rust
pub struct Pixel {
    r: integer limit(0, 255) not null,
    g: integer limit(0, 255) not null,
    b: integer limit(0, 255) not null
}
```

Data per pixel of the png graph. Fields r, g, b hold red, green and blue intensity, each 0–255.

```rust
pub struct Image {
    name: text,
    width: integer,
    height: integer,
    data: vector<Pixel>
}
```

Database structure with image data. The actual data is in height rows of width length.

```rust
pub enum Format {
    TextFile,
    LittleEndian,
    BigEndian,
    Directory,
    NotExists
}
```

Describes how a file is opened. TextFile: read or write as UTF-8 text (default). LittleEndian: binary mode, least-significant byte first. BigEndian: binary mode, most-significant byte first. Directory: represents a directory path. NotExists: no file or directory exist.

```rust
pub struct File {
    path: text,
    size: long,
    format: Format,
    ref: i32,
    current: long,
    next: long
}
```

A handle to a filesystem entry. Fields: path (full path), size (file size in bytes), format (open mode), current (byte position after last read), next (byte position to read next).

```rust
pub fn value(self: Pixel) -> integer
```

Returns the pixel colour as a packed 24-bit integer (0xRRGGBB). Use for fast colour comparison or storage.

```rust
pub fn content(self: File) -> text
```

Reads the entire file as a UTF-8 text value. Use for small configuration files or scripts.

```rust
pub fn lines(self: File) -> vector<text>
```

Reads the file and splits it into lines. Use when processing line-by-line (logs, CSV, etc.).

```rust
pub fn split(self: text, separator: character) -> vector<text>
```

Splits self on every occurrence of separator and returns the parts as a vector. Use to parse CSV lines or space-separated tokens.

```rust
pub fn file(path: text) -> File
```

Use as the entry point for all file I/O. Paths outside the project directory are treated as NotExists without touching the filesystem.

```rust
pub fn exists(path: text) -> boolean
```

Use to check whether a path is accessible before reading or writing it. Paths outside the project directory are always absent.

```rust
pub fn delete(path: text) -> boolean
```

Use to remove a file after processing or as a cleanup step. Returns false when the file did not exist or is outside the project directory.

```rust
pub fn move(from: text, to: text) -> boolean
```

Use to rename or relocate a file within the project. Both paths must stay within the project directory; the destination must not already exist.

```rust
pub fn set_file_size(self: File, size: long) -> boolean
```

Truncate or extend the file to exactly `size` bytes. Truncating removes bytes beyond `size`; extending fills with null bytes. Returns false if the file is a directory, does not exist, or `size` is negative. Any open handle to the file is closed; reopen the file for further I/O.

```rust
pub fn files(self: File) -> vector<File>
```

Returns the entries inside a directory. The File must have format == Format.Directory. Use to iterate over all files in a folder.

```rust
pub fn write(self: File, v: text)
```

Writes v as UTF-8 text to the file. Overwrites existing content.

```rust
pub fn png(self: File) -> Image
```

Decodes a PNG file and returns an Image. Returns null if the file is not in text format. Use to load sprite sheets or textures.

```rust
pub fn env_variables() -> vector<EnvVariable>
```

Returns all environment variables as a vector of EnvVariable records (fields: name, value). Use to inspect or forward the full environment.

```rust
pub fn env_variable(name: text) -> text
```

Returns the value of the environment variable name, or null if it is not set. Use to read configuration from the shell environment.

== Environment

Functions for interacting with the host operating system.

```rust
pub fn arguments() -> vector<text>
```

Returns the command-line arguments passed to the program. The first element is typically the program name.

```rust
pub fn directory(v: &text = "") -> text
```

Returns the current working directory, optionally with v appended as a subpath. Use to construct absolute paths relative to where the program was launched.

```rust
pub fn user_directory(v: &text = "") -> text
```

Returns the current user's home directory, optionally with v appended. Use for storing user-specific data or configuration.

```rust
pub fn program_directory(v: &text = "") -> text
```

Returns the directory containing the running executable, optionally with v appended. Use to locate assets bundled alongside the program.

